services:
  bot:
    build:
      context: .
      dockerfile: bot/dev.dockerfile
    environment:
      DEBUG: True
      TASKCLUSTER_URL: "https://firefox-ci-tc.services.mozilla.com/"
    volumes:
      - ./build/cache:/src/bot/build/cache
      - ./build/work:/src/bot/build/work
    ports:
      - 8000:8000
    networks:
      - codecov
  backend:
    build:
      context: .
      dockerfile: backend/dev.dockerfile
    environment:
      LOCAL_CONFIGURATION: "/src/backend/code-coverage.yml"
      DEBUG: True
    ports:
      - "8080:8080"
    networks:
      - codecov
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /tmp/ccov-redis:/data
    networks:
      - codecov
  frontend:
    build:
      context: .
      dockerfile: frontend/dev.dockerfile
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=code-coverage.local
     - NGINX_PORT=80
    networks:
      - codecov

networks:
  codecov: {}